int main()
{
	try
	{
		
	}
	catch (const exception &e)
	{
		cerr << e.what() << endl;
		abort();
	}
	return 0;
}